#!/usr/bin/env python3
"""Generate MAME per-game cfg files with rotate=270 (Myzar vertical CRT)."""
from __future__ import annotations

import argparse
import glob
import os
import sys

TEMPLATE = """<?xml version="1.0"?>
<!-- This file is autogenerated; comments and unknown tags will be stripped -->
<mameconfig version="10">
    <system name="{name}">
        <video>
            <target index="0" rotate="270" />
        </video>
    </system>
</mameconfig>
"""


def write_cfg(cfg_dir: str, name: str) -> str:
    path = os.path.join(cfg_dir, f"{name}.cfg")
    with open(path, "w", encoding="utf-8") as f:
        f.write(TEMPLATE.format(name=name))
    return path


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate MAME rotate=270 cfg files")
    parser.add_argument(
        "--rom-dir",
        default=os.environ.get("MAME_ROM_DIR", "/userdata/roms/mame"),
        help="Directory containing .zip ROMs",
    )
    parser.add_argument(
        "--cfg-dir",
        default=os.environ.get("MAME_CFG_DIR", "/userdata/system/configs/mame"),
        help="Output directory for .cfg files",
    )
    parser.add_argument(
        "--only",
        action="append",
        default=[],
        help="Generate only these basenames (repeatable). Without .zip",
    )
    args = parser.parse_args()

    os.makedirs(args.cfg_dir, exist_ok=True)
    zips = sorted(glob.glob(os.path.join(args.rom_dir, "*.zip")))
    if args.only:
        allowed = {n.removesuffix(".zip") if n.endswith(".zip") else n for n in args.only}
        zips = [z for z in zips if os.path.splitext(os.path.basename(z))[0] in allowed]

    if not zips:
        print(f"No .zip files in {args.rom_dir}", file=sys.stderr)
        return 1

    count = 0
    for path in zips:
        name = os.path.splitext(os.path.basename(path))[0]
        write_cfg(args.cfg_dir, name)
        count += 1

    print(f"Wrote {count} cfg file(s) to {args.cfg_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
