#!/usr/bin/env python3
"""Validate MAME rotate cfg files match ROM basenames and rotate=270."""
from __future__ import annotations

import argparse
import glob
import os
import re
import sys

EXPECTED_COMMENT = "<!-- This file is autogenerated; comments and unknown tags will be stripped -->"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--rom-dir", default="/userdata/roms/mame")
    parser.add_argument("--cfg-dir", default="/userdata/system/configs/mame")
    args = parser.parse_args()

    bad: list[str] = []
    zips = glob.glob(os.path.join(args.rom_dir, "*.zip"))
    for zp in sorted(zips):
        base = os.path.splitext(os.path.basename(zp))[0]
        cp = os.path.join(args.cfg_dir, f"{base}.cfg")
        if not os.path.isfile(cp):
            bad.append(f"{base}: missing cfg")
            continue
        text = open(cp, encoding="utf-8").read()
        if EXPECTED_COMMENT not in text:
            bad.append(f"{base}: wrong or extra comments")
        m = re.search(r'<system name="([^"]+)"', text)
        if not m or m.group(1) != base:
            bad.append(f"{base}: system name {m.group(1) if m else '?'} != {base}")
        if 'rotate="270"' not in text:
            bad.append(f"{base}: rotate is not 270")

    print(f"roms: {len(zips)}")
    print(f"mismatches: {len(bad)}")
    for line in bad[:50]:
        print(line)
    if len(bad) > 50:
        print(f"... and {len(bad) - 50} more")
    return 0 if not bad else 1


if __name__ == "__main__":
    raise SystemExit(main())
